name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync files to Droplet
      run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git*' ./ root@192.81.211.96:/var/www/html/

    - name: Restart Nginx (optional)
      run: ssh -o StrictHostKeyChecking=no root@192.81.211.96 'systemctl restart nginx'

